server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
      token: wx810b937ef508ce8e
    #配置一个文字的模板ID
    singleTemplateId:	 1ffec66d50ad9f37ad668114942a9793
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: 	oWhRg4sAkDG_eBncxW52mlpHal8D1kalF-QpB8_BORY
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds: oVy2p5tfPBcUYELNZMDWOWGNPQPw
#          - oK0U562Y5ijqYRpGUtNRs0vxxxWU
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 今天又是爱臭宝的一天！
            #你们的相遇时间
            meetDate: '2022-04-19'
            city: 驻马店
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 411725
            constellation: 射手座
          #把‘填写你的需要特定配置的微信用户号’覆盖位微信用户ID，可以对照正确填写好的配置示例，多用户可以按照格式继续添加下去
          填写你的需要特定配置的微信用户号: oVy2p5tfPBcUYELNZMDWOWGNPQPw
            title: 早上好呀呀鸭
            meetDate: '2021-08-11'
            city: 肇庆
            cityCode: 440600
            constellation: 狮子座
      #颜文字模板
      emoticonsTemplate:
        templateId: oWhRg4sAkDG_eBncxW52mlpHal8D1kalF-QpB8_BORY
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 双子座

